#!/usr/bin/env osascript

on run argv
	set old to (path to frontmost application as text)
	set telegramApp to "Telegram"
	set hasVersion to 0
	set msg to "Use the following commands:\n"
  	set msg to msg & "  telegram [message text] [repeat count]   - Send message text repeat count times\n"
  	set msg to msg & "  telegram [-h] [--help]                   - Show Help\n"
  
	if count of argv is equal to 0 then
		return msg
	end if

	if item 1 of argv as text is equal to "2" then
		set telegramApp to "Telegram 2"
		log 100
		set hasVersion to 1
	end if 
	log telegramApp
	tell Application telegramApp
		reopen
		activate
	end tell
	set flag to true
	set counts to 0
	set endSend to item (2 + hasVersion) of argv as number
	set InputPM to item (1 + hasVersion) of argv
	repeat while flag
		set counts to counts + 1
		tell application "System Events"
			keystroke InputPM
			keystroke return
			delay 0.085
		end tell
		if counts is equal to endSend then set flag to false
	end repeat
	activate application old

end run
